OutOfSchool/Controllers/OrganizationController.cs
OutOfSchool/OutOfSchool.csproj
OutOfSchool/OutOfSchool.sln
OutOfSchool/Program.cs
OutOfSchool/Properties/launchSettings.json
OutOfSchool/Startup.cs
OutOfSchool/appsettings.Development.json
OutOfSchool/appsettings.json

Add Out of School skeleton project. Connect Swagger packages. Create an empty Organization Controller.

Add Out of School skeleton project

---

.gitignore
OutOfSchool/IdentityServer/Controllers/AuthController.cs

Fixed assignment to properties in constructor

HotFix injection

---

Config/SQLQuery_insert test values.sql

Changed statuses for created applications, as they should be now in range from 1 to 5.

update script for applications create

---

OutOfSchool/OutOfSchool.DataAccess/Models/Provider.cs
OutOfSchool/OutOfSchool.DataAccess/OutOfSchoolDbContext.cs
OutOfSchool/OutOfSchool.DataAccess/Repository/EntityRepository.cs
OutOfSchool/OutOfSchool.DataAccess/Repository/ProviderRepository.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20210831171522_ActualAddressCanBeNull.Designer.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20210831171522_ActualAddressCanBeNull.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ProviderControllerTests.cs
OutOfSchool/OutOfSchool.WebApi.Tests/OutOfSchool.WebApi.Tests.csproj
OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServiceTests.cs
OutOfSchool/OutOfSchool.WebApi/Common/IdentityResourceClaimsTypes.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/ProviderController.cs
OutOfSchool/OutOfSchool.WebApi/Extensions/ClaimsPrincipalExtentions.cs
OutOfSchool/OutOfSchool.WebApi/Models/AddressDto.cs
OutOfSchool/OutOfSchool.WebApi/Models/ProviderDto.cs
OutOfSchool/OutOfSchool.WebApi/Services/IProviderService.cs
OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs
OutOfSchool/OutOfSchool.sln
OutOfSchool/Tests/OutOfSchool.Tests.Common/OutOfSchool.Tests.Common.csproj
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/AddressGenerator.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ProvidersGenerator.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/RatingsGenerator.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataHelper.cs

updated create repository flow.

---

README.md
add-hosts.ps1
docker-build.ps1
docker-compose.ps1

Due to poor performance of Vagrant on Windows, I've added PS scripts and documentation in readme with required tools to run this on Docker using WSL 2 backend (it might work on Hyper-V backend but no promises).
Readme section is titled **Windows 10 Alternative**

add docker env with WSL backend

---

OutOfSchool/OutOfSchool.IdentityServer/Controllers/AuthController.cs
OutOfSchool/OutOfSchool.IdentityServer/ViewModels/RegisterViewModel.cs
OutOfSchool/OutOfSchool.IdentityServer/Views/Auth/Register.cshtml

If add parameter "ProviderRegistration=true" to Login or Registration URL then will be opened Registration page with active tab "Service provider"

Add posibility to open provider registration page through parameter

---

OutOfSchool/OutOfSchool.WebApi/Startup.cs

Added singleton so service provider knows what it needs to inject as hostedservice

elastic pinger DI fix

---

OutOfSchool/OutOfSchool.ElasticsearchData/Models/AddressES.cs
OutOfSchool/OutOfSchool.ElasticsearchData/Models/DateTimeRangeES.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ElasticsearchWorkshopController.cs
OutOfSchool/OutOfSchool.WebApi/Extensions/ElasticsearchMappingExtensions.cs
OutOfSchool/OutOfSchool.WebApi/Models/AddressDto.cs
OutOfSchool/OutOfSchool.WebApi/Models/WorkshopFilter.cs

SearchResultES.cs now has mapper for AddressES, so latitude and Longitude can be mapped
DateTimeRangeES.cs Id property now has Guid type

mapping for SearchResultES changed, DateTimeRangeES id changed

---

OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
OutOfSchool/OutOfSchool.WebApi/Extensions/MappingExtensions.cs

Create, GetById, GetbyProviderId, GetAll, Update is covered by tests. All written tests are passed.

Added tests for workshopService.

---

OutOfSchool/OutOfSchool.Common/GeoMathHelper.cs
OutOfSchool/OutOfSchool.DataAccess/Models/City.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/CityController.cs
OutOfSchool/OutOfSchool.WebApi/Extensions/GeoMathHelperExtensions.cs
OutOfSchool/OutOfSchool.WebApi/Models/CityFilter.cs
OutOfSchool/OutOfSchool.WebApi/Services/CityService.cs
OutOfSchool/OutOfSchool.WebApi/Services/ICityService.cs

Functionality for getting the nearest city by latitude and longitude was added

#488 Functionality for getting the nearest city by latitude and longitude

---

OutOfSchool/OutOfSchool.IdentityServer/Views/Auth/Login.cshtml
OutOfSchool/OutOfSchool.IdentityServer/Views/Auth/Register.cshtml
OutOfSchool/OutOfSchool.IdentityServer/wwwroot/css/site.css

The task https://github.com/ita-social-projects/OoS-Frontend/issues/744

Remove social block

---

OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.en.resx
OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.uk.resx
OutOfSchool/OutOfSchool.IdentityServer/Views/Account/Email/ChangeEmail.cshtml
OutOfSchool/OutOfSchool.IdentityServer/Views/Account/Password/ChangePassword.cshtml

The task https://github.com/ita-social-projects/OoS-Frontend/issues/838
1. Add translation
2. Remove unnecessary parenthese in the code.

feat: add ukrainian translation for the button save

---

OutOfSchool/OutOfSchool.IdentityServer/Controllers/AuthController.cs
OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.uk.resx
OutOfSchool/OutOfSchool.IdentityServer/Startup.cs
OutOfSchool/OutOfSchool.IdentityServer/ViewModels/RegisterViewModel.cs

Registration page is changing localisation. Fix some errors.

#790 Issue in Frontend project.

---

OutOfSchool/OutOfSchool.IdentityServer/Views/Account/Password/ForgotPassword.cshtml

[Log in] The ‘Відновити пароль’ page does not meet the design

[Log in] The ‘Відновити пароль’ page does not meet the design

---

OutOfSchool/OutOfSchool.Common/Models/ResponseDto.cs
OutOfSchool/OutOfSchool.IdentityServer/Controllers/ProviderAdminController.cs
OutOfSchool/OutOfSchool.IdentityServer/Services/Interfaces/IProviderAdminService.cs
OutOfSchool/OutOfSchool.IdentityServer/Services/ProviderAdminService.cs
OutOfSchool/OutOfSchool.IdentityServer/Startup.cs
OutOfSchool/OutOfSchool.IdentityServer/appsettings.Development.json
OutOfSchool/OutOfSchool.IdentityServer/appsettings.Google.json
OutOfSchool/OutOfSchool.IdentityServer/appsettings.Kubernetes.json
OutOfSchool/OutOfSchool.WebApi/Extensions/Startup/SwaggerExtensions.cs

fixed transaction error roll back when email fails to send

---

OutOfSchool/OutOfSchool.Common/IdentityResourceClaimsTypes.cs
OutOfSchool/OutOfSchool.DataAccess/Enums/Subrole.cs
OutOfSchool/OutOfSchool.DataAccess/Repository/ChatRoomWorkshopModelForChatListRepository.cs
OutOfSchool/OutOfSchool.DataAccess/Repository/IChatRoomWorkshopModelForChatListRepository.cs
OutOfSchool/OutOfSchool.IdentityServer/ProfileService.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Hubs/ChatWorkshopHubTests.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Services/ValidationServiceTests.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChatWorkshopController.cs
OutOfSchool/OutOfSchool.WebApi/Hubs/ChatWorkshopHub.cs
OutOfSchool/OutOfSchool.WebApi/Services/ChatRoomWorkshopService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IChatRoomWorkshopService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IProviderAdminService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IValidationService.cs
OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs
OutOfSchool/OutOfSchool.WebApi/Services/ValidationService.cs

Functionality for provider's deputy and provider's admin was added

Romanchuk lukashov/chat provider admin add

---

app-cloudbuild.yml
auth-cloudbuild.yml

about 10% time reduction that will help us stay in the free daily 120 minutes quota

add cache to save container build time

---

OutOfSchool/OutOfSchool.IdentityServer/wwwroot/css/site.css

Task https://github.com/ita-social-projects/OoS-Frontend/issues/680

fix: add styles for the phone number code

---

OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs

Fix exception when the list of ratings with type=1 for Providers is empty

Bug fix NullReferenceException

---

OutOfSchool/OutOfSchool.DataAccess/Enums/InstitutionType.cs
OutOfSchool/OutOfSchool.DataAccess/Models/Configurations/ProviderConfiguration.cs
OutOfSchool/OutOfSchool.DataAccess/Models/Provider.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20220525090250_AddColumnProviderInstitutionType.Designer.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20220525090250_AddColumnProviderInstitutionType.cs
OutOfSchool/OutOfSchool.WebApi/Models/ProviderDto.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ProviderDtoGenerator.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ProvidersGenerator.cs

Added:
-  new enum - InstitutionType;
-  new column InstitutionType to the Provider.

R biyovskiy/632 sp cabinet тип закладу block is missing in the description of institution

---

app-cloudbuild.yml
auth-cloudbuild.yml

First successful build will check and increment the tag if needed

update cloudbuild to implement automatic deploy

---

OutOfSchool/OutOfSchool.WebApi.Tests/Services/ClassServiceTests.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Services/DepartmentServiceTests.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Services/DirectionServiceTests.cs

As classes, departments & directions will be completely reworked - mark tests obsolete and ready to be removed

mark obsolete test for soon to be refactored funtionality

---

OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ChildControllerTests.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ParentControllerTests.cs
OutOfSchool/OutOfSchool.WebApi/Models/ChildDTO.cs
OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ChildDtoGenerator.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ParentDtoWithContactInfoGenerator.cs

Resolves: #986
ChildDTO.Parent changed from ParentDTO to ParentDtoWithContactInfo
Need to show information about child and his parent simultaneously

Parent details in ChildDTO

---

OutOfSchool/OutOfSchool.ElasticsearchData/ESWorkshopProvider.cs

**Changes:**
- ElastichSearch sorts worskhops by given Order by parameter and then by alphabet

made workshop filter to always sort by alphabet

---

OutOfSchool/OutOfSchool.Common/Constants.cs
OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.en.resx
OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.uk.resx
OutOfSchool/OutOfSchool.IdentityServer/ViewModels/RegisterViewModel.cs
OutOfSchool/OutOfSchool.IdentityServer/Views/Auth/Register.cshtml
OutOfSchool/OutOfSchool.IdentityServer/wwwroot/css/site.css
OutOfSchool/OutOfSchool.IdentityServer/wwwroot/js/site.js

Linked issues:
1) Incorrect password message https://github.com/ita-social-projects/OoS-Frontend/issues/1157
2) Validation message for text inputs https://github.com/ita-social-projects/OoS-Frontend/issues/1154
3) Middle name required (it was change to require don front, confirmed with BA)
4) Disable the submit button when the checkbox is not checked https://github.com/ita-social-projects/OoS-Frontend/issues/1147
5) additional text under REGISTER https://github.com/ita-social-projects/OoS-Frontend/issues/1131
6) validation message for password https://github.com/ita-social-projects/OoS-Frontend/issues/1130

[Registration form] - general UI bug fix

---

OutOfSchool/OutOfSchool.DataAccess/Models/Teacher.cs
OutOfSchool/OutOfSchool.DataAccess/Models/User.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20220616154207_UserTeacherGender.Designer.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20220616154207_UserTeacherGender.cs
OutOfSchool/OutOfSchool.WebApi/Models/ShortUserDto.cs
OutOfSchool/OutOfSchool.WebApi/Models/Teachers/TeacherDTO.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/TeachersGenerator.cs

added gender to user (for parent)
added gender to  teacher

add user, teacher gender

---

OutOfSchool/OutOfSchool.WebApi/Services/StatisticService.cs
OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/IInstitutionFieldDescriptionService.cs
OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/IInstitutionHierarchyService.cs
OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/IInstitutionService.cs
OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/InstitutionFieldDescriptionService.cs
OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/InstitutionHierarchyService.cs
OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/InstitutionService.cs

Add Redis to InstitutionHierarchy services:
- InstitutionFieldDescriptionService.GetByInstitutionId
- InstitutionHierarchyService.GetChildren
- InstitutionHierarchyService.GetParents
- InstitutionHierarchyService.GetAllByInstitutionAndLevel
- InstitutionService.GetAll

Romanchuk/Add Redis to institution hierarchy

---

OutOfSchool/OutOfSchool.DataAccess/Models/Configurations/ProviderConfiguration.cs
OutOfSchool/OutOfSchool.DataAccess/Models/Provider.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20220622143956_RemoveProviderDescription.Designer.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20220622143956_RemoveProviderDescription.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Extensions/MappingExtensionsTests.cs
OutOfSchool/OutOfSchool.WebApi/Extensions/MappingExtensions.cs
OutOfSchool/OutOfSchool.WebApi/Models/ProviderDto.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ProviderDtoGenerator.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ProvidersGenerator.cs

* Property Provider.Description Deleted

Hot fix: remove provider description

---

OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs

fixed mapping for the Provider.SectionName

---

OutOfSchool/OutOfSchool.WebApi/Controllers/V2/ProviderController.cs

Fixed response

---

OutOfSchool/OutOfSchool.IdentityServer/appsettings.Development.json
OutOfSchool/OutOfSchool.IdentityServer/appsettings.Google.json
OutOfSchool/OutOfSchool.IdentityServer/appsettings.GooglePreRelease.json
OutOfSchool/OutOfSchool.IdentityServer/appsettings.json
OutOfSchool/OutOfSchool.WebApi/appsettings.Development.json
OutOfSchool/OutOfSchool.WebApi/appsettings.Google.json
OutOfSchool/OutOfSchool.WebApi/appsettings.GooglePreRelease.json
OutOfSchool/OutOfSchool.WebApi/appsettings.Kubernetes.json
OutOfSchool/OutOfSchool.WebApi/appsettings.json

Restore Serilog settings that we had before migration to .NET 6 to have enough information.

Restore logging settings

---

OutOfSchool/OutOfSchool.DataAccess/Models/ChatWorkshop/ModelsForChatLists/ParentInfoForChatList.cs
OutOfSchool/OutOfSchool.DataAccess/Repository/ChatRoomWorkshopModelForChatListRepository.cs
OutOfSchool/OutOfSchool.IdentityServer/Controllers/AuthController.cs
OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.en.resx
OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.uk.resx
OutOfSchool/OutOfSchool.IdentityServer/ViewModels/RegisterViewModel.cs
OutOfSchool/OutOfSchool.IdentityServer/Views/Auth/Register.cshtml
OutOfSchool/OutOfSchool.IdentityServer/wwwroot/css/site.css
OutOfSchool/OutOfSchool.WebApi.Tests/Extensions/MappingExtensionsTests.cs
OutOfSchool/OutOfSchool.WebApi/Extensions/MappingExtensions.cs
OutOfSchool/OutOfSchool.WebApi/Models/MinistryAdminDto.cs
OutOfSchool/OutOfSchool.WebApi/Models/ParentDtoWithContactInfo.cs
OutOfSchool/OutOfSchool.WebApi/Models/ProviderAdminDto.cs
OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs

* added resource localization for gender
* modified register page

User registration with gender

---

OutOfSchool/OutOfSchool.DataAccess/Models/SubordinationStructure/Institution.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChatWorkshopController.cs
OutOfSchool/OutOfSchool.WebApi/Services/IMinistryAdminService.cs
OutOfSchool/OutOfSchool.WebApi/Services/MinistryAdminService.cs

**_For Ministry Admins:_**
- Added ability to get chat rooms by **Provider Id**  if **Provider** is a subordinate of **Ministry Admin**.
- Added ability to see chat messages in allowed rooms (where **Provider** is a subordinate).
- Added **Operation handler** in order to avoid duplicates.

Added ability to see providers' chats for ministry admins

---

OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ApplicationController.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/RatingController.cs
OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IApplicationService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IRatingService.cs
OutOfSchool/OutOfSchool.WebApi/Services/RatingService.cs

- Add IsRewiewed to rating controller
- Fix AllowedToReview: add workshopId to predicat filter

Romanchuk/Add IsRewiewed to rating controller

---

OutOfSchool/OutOfSchool.RazorTemplatesData/Views/Emails/ResetPassword/ResetPassword.cshtml
OutOfSchool/OutOfSchool.RazorTemplatesData/Views/Shared/EmailButton.cshtml
OutOfSchool/OutOfSchool.RazorTemplatesData/Views/Shared/EmailLayout.cshtml

1) Fix email templates
2) Fix styles according to templates in Figma https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=13045%3A7042

Fix image path and styles

---

OutOfSchool/OutOfSchool.WebApi.Tests/Extensions/ElasticSearchMappingExtensionsTests.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/WorkshopDtoGenerator.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/WorkshopESGenerator.cs

Added 2 generators for WorkshopES and WorkshopDto
Added tests for mapping extention

Generators and tests added

---

OutOfSchool/OutOfSchool.WebApi/Models/Changes/ChangesLogFilterBase.cs
OutOfSchool/OutOfSchool.WebApi/Models/Changes/ProviderAdminChangesLogRequest.cs
OutOfSchool/OutOfSchool.WebApi/Services/ChangesLogService.cs

Add search string to ChangeLog filter

---

OutOfSchool/OutOfSchool.IdentityServer/db-scripts.txt
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChildController.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/WorkshopController.cs
OutOfSchool/OutOfSchool.WebApi/Models/ShortEntityDto.cs
OutOfSchool/OutOfSchool.WebApi/Services/ChildService.cs
OutOfSchool/OutOfSchool.WebApi/Services/Database/IWorkshopService.cs
OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IChildService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IWorkshopServicesCombiner.cs
OutOfSchool/OutOfSchool.WebApi/Services/WorkshopServicesCombiner.cs
OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs

#811
GetWorkshopListByProviderId
GetChildrenListByParentId

Add endpoints

---

OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/MinistryAdminControllerTests.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Services/MinistryAdminServiceTests.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/AdminGenerator.cs

Tests for GetByFilter and GetId methods for MinistryAdmin have been added

Tests for MinistryAdmin

---

OutOfSchool/OutOfSchool.WebApi/Controllers/V1/MinistryAdminController.cs
OutOfSchool/OutOfSchool.WebApi/Services/MinistryAdminService.cs

Using endpoint MinistryAdmin/Create User entity is created too. And if email already exists in the registered user's list then an error will appear. The method to avoid this case has been added

Checking email when MinistryAdmin is created

---

OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/WorkshopControllerTests.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/WorkshopController.cs
OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopCard.cs
OutOfSchool/OutOfSchool.WebApi/Services/Database/IWorkshopService.cs
OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IProviderAdminService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IWorkshopServicesCombiner.cs
OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs
OutOfSchool/OutOfSchool.WebApi/Services/WorkshopServicesCombiner.cs
OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/WorkshopBaseCardGenerator.cs

1) Fix V2/WorkshopController/Create - setup workshop.Status to Open by default
2) Add new shortened WorkshopCard
3) Change returned values in 2 methods
4) Add mapping

Add WorkshopViewProviderCard

---

OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ProviderAdminController.cs
OutOfSchool/OutOfSchool.WebApi/Services/IProviderAdminService.cs
OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs

The returned value has been changed from WorkshopBaseCard to WorkshopProviderViewCard in ProviderAdmin/ManagedWorkshops endpoint

Fix ManagedWorkshops returned value

---

OutOfSchool/OutOfSchool.DataAccess/Models/Workshop.cs
OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopDTO.cs

As per new user story rules we have up to `100_000`price range

update price validation

---

OutOfSchool/OutOfSchool.IdentityServer.Tests/Controllers/AccountControllerTests.cs
OutOfSchool/OutOfSchool.IdentityServer.Tests/Controllers/AuthControllerTests.cs
OutOfSchool/OutOfSchool.IdentityServer/Controllers/AccountController.cs
OutOfSchool/OutOfSchool.IdentityServer/Controllers/AuthController.cs
OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.en.resx
OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.uk.resx
OutOfSchool/OutOfSchool.IdentityServer/Views/Account/Password/ForgotPassword.cshtml
OutOfSchool/OutOfSchool.IdentityServer/Views/Account/Password/ForgotPasswordConfirmation.cshtml
OutOfSchool/OutOfSchool.IdentityServer/Views/Auth/ConfirmEmail.cshtml

- add sending an email during the confirmation email process
- fix confirmation email process
- add checking is valid token during email confirmation process
- add checking is email confirmed during reset password confirmation process
- add string resources for messages
- fix views

Baditsa/registration confirmation 

---

OutOfSchool/OutOfSchool.DataAccess/Models/Provider.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20221018081520_ProviderStatusReason.Designer.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20221018081520_ProviderStatusReason.cs
OutOfSchool/OutOfSchool.WebApi/Models/Providers/ProviderDto.cs
OutOfSchool/OutOfSchool.WebApi/Models/Providers/ProviderStatusDto.cs
OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs

Provider Status Reason added

---

OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/AchievementControllerTest.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Services/AchievementServiceTest.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/AchievementController.cs
OutOfSchool/OutOfSchool.WebApi/Models/Achievement/AchivementsFilter.cs
OutOfSchool/OutOfSchool.WebApi/Services/AchievementService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IAchievementService.cs

Added pagination to Achievements 

---

OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/WorkshopControllerTests.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/WorkshopController.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V2/WorkshopController.cs
OutOfSchool/OutOfSchool.WebApi/Services/Database/IWorkshopService.cs
OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IWorkshopServicesCombiner.cs
OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs
OutOfSchool/OutOfSchool.WebApi/Services/WorkshopServicesCombiner.cs
OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ShortEntityDtoGenerator.cs

issue #857 
added offset filter (pagination) to:
1) v1/GetWorkshopProviderViewCardsByProviderId
2) v1/GetWorkshopListByProviderId
3) v1/GetByProviderId

Added pagination to Workshops and Workshops View Cards

---

OutOfSchool/OutOfSchool.DataAccess/CalculateGeoHashInterceptor.cs
OutOfSchool/OutOfSchool.DataAccess/Models/Address.cs
OutOfSchool/OutOfSchool.DataAccess/OutOfSchoolDbContext.cs
OutOfSchool/OutOfSchool.ElasticsearchData/ESWorkshopProvider.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20221114231452_AddGeoHashToAddress.Designer.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20221114231452_AddGeoHashToAddress.cs
OutOfSchool/OutOfSchool.WebApi/Services/CodeficatorService.cs
OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
OutOfSchool/OutOfSchool.WebApi/Services/Strategies/WorkshopStrategies/WorkshopServiceStrategy.cs
OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs

Add GeoHash to Address

---

OutOfSchool/OutOfSchool.DataAccess/Models/Configurations/CodeficatorConfiguration.cs
OutOfSchool/OutOfSchool.DataAccess/OutOfSchoolDbContext.cs
OutOfSchool/OutOfSchool.DataAccess/Repository/CodeficatorRepository.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20221124171147_IsTopToCodeficator.Designer.cs
OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20221124171147_IsTopToCodeficator.cs
OutOfSchool/OutOfSchool.WebApi/Models/Codeficator/CodeficatorFilter.cs

Add top cities response to codeficator's search query

---

OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ProviderAdminController.cs
OutOfSchool/OutOfSchool.WebApi/Models/ProviderAdminSearchFilter.cs
OutOfSchool/OutOfSchool.WebApi/Models/SearchStringFilter.cs
OutOfSchool/OutOfSchool.WebApi/Services/IProviderAdminService.cs
OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs

Pagination and searchString were added

---

OutOfSchool/OutOfSchool.WebApi/Models/ParentDtoWithContactInfo.cs
OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs

Romanchuk/Add EmailConfirmed to ParentDto model

---

OutOfSchool/OutOfSchool.WebApi/Controllers/V1/RatingController.cs
OutOfSchool/OutOfSchool.WebApi/Services/IRatingService.cs
OutOfSchool/OutOfSchool.WebApi/Services/RatingService.cs

Result was switched to SearchResult type

Romanchuk/Fix rating GetAllByEntityId

---

OutOfSchool/OutOfSchool.Common/Models/UserRights.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ProviderAdminController.cs
OutOfSchool/OutOfSchool.WebApi/Services/CurrentUserService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IProviderAdminService.cs
OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs

Get provider admin by Id

---

OutOfSchool/OutOfSchool.WebApi/Services/CodeficatorService.cs

Fix https://github.com/ita-social-projects/OoS-Frontend/issues/1879

Romanchuk / Fix geocoding mapping

---

OutOfSchool/OutOfSchool.WebApi.Tests/Services/ChatMessageWorkshopServiceTests.cs
OutOfSchool/OutOfSchool.WebApi/Services/ChatMessageWorkshopService.cs

Send "ReadChatMessagesByUser" to workshopHub by SignalR
closed #899

Romanchuk / Add mailing that the message has been read

---

OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServiceTests.cs
OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs
OutOfSchool/OutOfSchool.WebApi/Services/ProviderServiceV2.cs
OutOfSchool/Tests/OutOfSchool.WebApi.IntegrationTests/ProviderServiceIntergrationTests/ProviderServiceUpdate.cs

Notify admins that provider updated

---

OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs

Frontend did not specify correctly what they needed on the first try :)

change search by parent to search by child

---

OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChatWorkshopController.cs

Add endpoint "parent/workshops/{id}/messages"

Romanchuk / Get messages for parent

---

OutOfSchool/OutOfSchool.IdentityServer/Controllers/ProviderAdminController.cs
OutOfSchool/OutOfSchool.IdentityServer/Services/Interfaces/IProviderAdminService.cs
OutOfSchool/OutOfSchool.IdentityServer/Services/ProviderAdminService.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ProviderAdminController.cs
OutOfSchool/OutOfSchool.WebApi/Services/Communication/CommunicationConstants.cs
OutOfSchool/OutOfSchool.WebApi/Services/IProviderAdminService.cs
OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs

Reinvite provideradmin

---

OutOfSchool/OutOfSchool.DataAccess/Enums/StatisticReportDataTypes.cs
OutOfSchool/OutOfSchool.DataAccess/Enums/StatisticReportTypes.cs

Attributes for string representation were added

Romanchuk / Statistic report enums

---

OutOfSchool/OutOfSchool.WebApi/Config/FeatureManagementConfig.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V2/ProviderController.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V2/TeacherController.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V2/WorkshopController.cs
OutOfSchool/OutOfSchool.WebApi/Enums/Feature.cs
OutOfSchool/OutOfSchool.WebApi/Extensions/Startup/SwaggerExtensions.cs
OutOfSchool/OutOfSchool.WebApi/Extensions/Startup/SwaggerFeatureGateFilter.cs
OutOfSchool/OutOfSchool.WebApi/appsettings.json

1. Add FeatureGate to v2 controllers.
2. Add document's filter to making swagger documentation.

Romanchuk / FeatureManagement

---

OutOfSchool/OutOfSchool.DataAccess/Enums/NotificationAction.cs
OutOfSchool/OutOfSchool.DataAccess/Enums/NotificationType.cs
OutOfSchool/OutOfSchool.WebApi/Common/QuartzConstants/JobConstants.cs
OutOfSchool/OutOfSchool.WebApi/Common/QuartzConstants/JobTriggerConstants.cs
OutOfSchool/OutOfSchool.WebApi/Config/Quartz/QuartzCronScheduleConfig.cs
OutOfSchool/OutOfSchool.WebApi/Extensions/Startup/NotificationExtensions.cs
OutOfSchool/OutOfSchool.WebApi/Services/LicenseApprovalNotification/ILicenseApprovalNotificationService.cs
OutOfSchool/OutOfSchool.WebApi/Services/LicenseApprovalNotification/LicenseApprovalNotificationQuartzJob.cs
OutOfSchool/OutOfSchool.WebApi/Services/LicenseApprovalNotification/LicenseApprovalNotificationService.cs
OutOfSchool/OutOfSchool.WebApi/Startup.cs
OutOfSchool/OutOfSchool.WebApi/appsettings.json

Tsylia/ Added yearly license approval notification.

---

OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs

Mapped MiddleName to string.Empty in Dtos if it's null.

Mapped MiddleName to string.Empty in Dtos if it's null.

---

Terraform/GCP/k8s/elastic.tf
Terraform/GCP/k8s/values/elastic.yaml
Terraform/GCP/k8s/variables.tf

add module mysql, kibana, redis to monitoring by metricbeat

add mysql,kibana,redis to metricbeat

---

OutOfSchool/OutOfSchool.DataAccess/Repository/IWorkshopRepository.cs
OutOfSchool/OutOfSchool.DataAccess/Repository/WorkshopRepository.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ApplicationControllerTests.cs
OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ApplicationController.cs
OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
OutOfSchool/OutOfSchool.WebApi/Services/IApplicationService.cs

#1089
Check for available seats was added to approving application.

Checking was added

---

OutOfSchool/OutOfSchool.IdentityServer.Tests/Controllers/AccountControllerTests.cs
OutOfSchool/OutOfSchool.IdentityServer/Controllers/AccountController.cs
OutOfSchool/OutOfSchool.IdentityServer/Views/Account/Password/ResetPasswordConfirmation.cshtml

Add login link on ResetPasswordConfirmation page

---

OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs

Fix update of workshop

---

OutOfSchool/OutOfSchool.DataAccess/Repository/WorkshopRepository.cs

Fix this at frontend repository
https://github.com/ita-social-projects/OoS-Frontend/issues/2098

Fix ProviderOwnership bug on workshop creating

---

OutOfSchool/OutOfSchool.IdentityServer/Services/ProviderAdminService.cs

Fix email confirmation
